const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

exports.createResultPdf = async (data, res) => {
  const doc = new PDFDocument({ margin: 40 });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", "attachment; filename=result.pdf");
  doc.pipe(res);

 
  const fontPath = path.join(__dirname, "../../fonts/NotoSans-Regular.ttf");
  if (fs.existsSync(fontPath)) {
    doc.font(fontPath);
  }

  const percentage = ((data.correct / data.total) * 100).toFixed(2);
  const status = percentage >= 40 ? "Pass" : "Fail";

  // ===== Title =====
  doc.fillColor("#1F4E79")
    .fontSize(24)
    .text("Exam Result Report", { align: "center", underline: true })
    .moveDown(1.5);

  // ===== Student Info =====
  doc.fillColor("#000")
    .fontSize(16)
    .text("Student Information", { underline: true })
    .moveDown(0.5);

  doc.fontSize(12)
    .text(`Name    : ${data.studentName || "Not Provided"}`)
    .text(`Email   : ${data.studentEmail || "Not Provided"}`)
    .text(`Contact : ${data.studentContact || "Not Provided"}`)
    .moveDown(1);

  // ===== Exam Summary =====
  const summaryTop = doc.y;
  doc.roundedRect(40, summaryTop, 520, 100).stroke("#4A90E2");

  doc.fontSize(14).fillColor("#000").text("Exam Summary", 50, summaryTop + 10);

  doc.fontSize(12)
    .text(`Total Questions : ${data.total}`, 60, summaryTop + 30)
    .text(`Correct Answers : ${data.correct}`)
    .text(`Wrong Answers   : ${data.wrong}`)
    .text(`Percentage      : ${percentage}%`)
    .text(`Status          : ${status}`);

  doc.moveDown(6);

  // ===== Answer Summary =====
  doc.fillColor("#000")
    .fontSize(16)
    .text("Answer Summary", { underline: true })
    .moveDown(0.5);

  data.resultDetails.forEach((q, idx) => {
    doc.fontSize(12).fillColor("#000")
      .text(`${idx + 1}. ${q.question}`)
      .text(`Your Answer     : ${q.submitted}`)
      .text(`Correct Answer  : ${q.correctOptionText} (Option ${q.correctOptionNumber})`)
      .fillColor(q.isCorrect ? "green" : "red")
      .text(`Result          : ${q.isCorrect ? "Correct" : "Wrong"}`)
      .fillColor("#000")
      .moveDown(0.8);
  });

  // ===== Footer =====
  doc.moveDown(2);
  doc.fontSize(10).fillColor("#555")
    .text("This report is confidential and generated by the Exam Application System", { align: "center" });

  doc.end();
};
